#!/usr/bin/env bash

# 1. Reload Xresources and terminals
xrdb -merge ~/.Xresources
pidof st | xargs kill -s USR1

# 2. Update Symlinks (Redundant rm commands removed)
ln -sf ~/.cache/wal/roficolors/pywal.rasi ~/.config/rofi/colors/pywal.rasi
ln -sf ~/.cache/wal/dunst ~/.config/dunst
ln -sf ~/.cache/wal/picom/shadow.conf ~/.config/picom/shadow.conf
ln -sf ~/.cache/wal/picom/wmshadow.conf ~/.config/wmaker/picom/shadow.conf
ln -sf ~/.cache/wal/pywalcava ~/.config/cava/themes/pywal
ln -sf ~/.cache/wal/gtk.css ~/.config/gtk-3.0/gtk.css
ln -sf ~/.cache/wal/gtk.css ~/.config/gtk-4.0/gtk.css
ln -sf ~/.cache/wal/wal ~/.config/wal.txt

# 3. Reload Daemons
pkill dunst
setsid -f dunst
pkill -USR1 cava

# 4. Reload Qutebrowser in the background
if pgrep -x "qutebrowser" > /dev/null; then
    qutebrowser ':config-source' &
fi

# 5. Load Cache Variables natively
. "$HOME/.cache/wal/backend.sh"
. "$HOME/.cache/wal/colors.sh"
. "$HOME/.cache/wal/lightmode.sh"

# Send initial notification immediately
notify-send "Wallpaper changed" "Backend: $BCKND"

# 6. Lockscreen Generation (Pushed to background)
RESIZE="$HOME/.cache/screenlock.png"

if [ "$LIGHTMD" = "true" ]; then
  BGCOL="$color15"
else
  BGCOL="$color0"
fi

# We wrap the heavy ImageMagick task in parentheses with an '&' 
# to run it silently in the background. The script finishes instantly!
(
    magick "$wallpaper" -resize 1366x768^ -gravity center -extent 1366x768 -fill "$BGCOL" -colorize 50% "$RESIZE"
    notify-send "Lockscreen has been updated"
) &

